// <auto-generated />
namespace RESAERCHMENTOR.NET_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ese_FM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ese_FM));
        
        string IMigrationMetadata.Id
        {
            get { return "201810241040441_Ese_FM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
